kumuluzee:
  name: vinjete
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://0.0.0.0:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/VinjeteDS
      connection-url: jdbc:postgresql://34.122.241.182:5432/vinjete
      pool:
        max-size: 20
  persistence-units:
    - name: "evinjete-vinjete"
      continue-on-error: false
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    consul:
      agent: http://hashicorp-consul-server.default.svc.cluster.local:8500
  discovery:
    ttl: 20
    ping-interval: 15
    consul:
      agent: http://hashicorp-consul-server.default.svc.cluster.local:8500
